services:
  jira-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-mcp-server
    ports:
      - "8090:8443"
    extra_hosts:
      - "qwen3-32b-awq.apps.k8s.ehd-zr.cbr.ru:10.1.6.100"
    networks:
      - mcp-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8443/health" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    environment:
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_AI_MCP=TRACE

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      ENABLE_OPENAI_API: "true"
      OPENAI_API_BASE_URLS: "http://sputnik.apps.k8s.ehd-zr.cbr.ru/api/v1"
      OPENAI_API_KEYS: "sk-09fd660cdc8640ac861fe85a16d2d2f1"
      ENABLE_TOOLS: "true"
      ENABLE_DIRECT_CONNECTIONS: "true"
      TOOL_SERVER_CONNECTIONS: '[{"url":"http://jira-mcp-server:8443/mcp","type":"mcp","path":"","auth_type":"none","key":"","config":{"enable":true},"info":{"id":"jira-tools-server","name":"Jira","description":"Jira tools"}}]'
      ENABLE_PERSISTENT_CONFIG: "false"
      ENABLE_OLLAMA: "false"
    depends_on:
      jira-mcp-server:
        condition: service_healthy
    networks:
      - mcp-network
    restart: always

networks:
  mcp-network:
    driver: bridge

volumes:
  open-webui: