# Настройки для разработки
spring.profiles.active=dev

# Основные настройки приложения
spring.application.name=test-system

# HTTPS настройки
server.port=8443
server.address=0.0.0.0
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:https-cert.p12
server.ssl.key-store-password=19216841223
server.ssl.key-alias=vaadin
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

# Опционально: HTTP порт для редиректа
# server.port-http=8080

# БЕЗ Thymeleaf - только статические ресурсы
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.cachecontrol.max-age=0

# Настройки JSON
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# Настройки логирования
logging.level.com.testsystem=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Настройки многопоточности
spring.task.execution.pool.core-size=4
spring.task.execution.pool.max-size=8
spring.task.execution.pool.queue-capacity=100

# Отключаем автоконфигурацию для template engines
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration

# Jira API
jira.username=
jira.password=
jira.writeTimeout=180
jira.readTimeout=180

# AI Service

#spring.ai.openai.base-url=https://qwen3-32b-awq.apps.k8s.ehd-zr.cbr.ru
#spring.ai.openai.chat.options.model=qwen3-32b-awq


spring.ai.openai.base-url=https://chat.ehd-zr.cbr.ru
spring.ai.openai.chat.options.model=Qwen/Qwen3.5-397B-A17B-GPTQ-Int4
#учетка ПИС
spring.ai.openai.chat.options.http-headers.Authorization=Bearer sk-09fd660cdc8640ac861fe85a16d2d2f1
spring.ai.openai.chat.completions-path=/openai/chat/completions


# DevTools LiveReload (дублирование)
spring.devtools.livereload.enabled=false
spring.devtools.restart.enabled=false

# Vaadin статистика (принудительно)
vaadin.launch-browser=false
vaadin.stats.opt-out=true


# Настройки безопасности
server.error.include-message=always
server.error.include-binding-errors=always

server.tomcat.socket.so-linger=-1

# Директория для сохранения готовых MD-файлов ответов по тест-кейсам
# Переопределите в application-dev.properties или через переменную окружения APP_READY_DIR
app.ready-dir=src/main/resources/example/ready
